volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - foodgram-network
  backend:
    image: maxkulmon/foodgram_backend
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - db:
          condition: service_healthy 
    networks: 
      - foodgram-network
  frontend:
    image: maxkulmon/foodgram_frontend 
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: maxkulmon/foodgram_gateway 
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend 
    networks:
      - foodgram-network

networks:
  foodgram-network:
    driver: bridge      
